name: CI Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: node:20

    steps:
      - uses: actions/checkout@v3

      - name: Write config.json from secret
        working-directory: ./backend/src
        run: |
          echo "$CONFIG_JSON" > config.json
        env:
          CONFIG_JSON: ${{ secrets.CONFIG_JSON }}

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Run tests
        working-directory: ./backend
        run: |
          npm start &
          SERVER_PID=$!
          timeout 10s bash -c 'until curl -s http://localhost:3228 > /dev/null; do sleep 1; done'

          # Run the tests
          npm test

          # Kill the server process
          kill $SERVER_PID