name: CI Tests

on:
  pull_request:
    branches:
      - main   # Run on PRs into main
 
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.13] # Test on multiple Node versions if you want

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'   # cache dependencies for faster runs

      - name: Install dependencies
        run: npm ci   # clean install based on package-lock.json

      - name: Run tests
        run: npm test